### ISSUE TITLE
能不能不要丢人

### ISSUE THREAD

**Issue by tonyqus** [Mapoet/OurNotepad#1]
fork过来，改了个名字，还把fork source去掉了，这样就成自己的项目了，这好像比原作者加stand with hk恶心多了。作为中科院PHD学生，能不能做点实事，别出来丢人现眼。Github有很多优秀的developer，请做些给中国人长脸的事，谢谢！

**Comment by Mapoet** [comment]
它是开源的代码，难道我不能修改？它stand with hk，我做一个新的版本不可以？我怎么丢人了？什么时候issue成了骂人的地方了？
